### ISSUE TITLE
Newer machines returning wrong estimated date of manufacture

### ISSUE THREAD

**Issue by sphen13** [munkireport/warranty#1]
I have noticed that new machines are showing as 10 years old (2010 instead of 2020).

I found someone else who used the same estimation formula and took the idea that if the machine has a T2 chip and if the calc thinks it was manufactured before 2018 add 10 years to the calc.

Not sure how one would implement something similar or have another solution.

https://github.com/univ-of-utah-marriott-library-apple/scl_jamf_extension_attribute_collection/blob/d338f48f502a61a944bc6e143c0d5489ba210569/estimated_date_of_manufacture.py#L62

**Comment by bochoven** [comment]
That’s unfortunate, not sure how to solve that elegantly. This may all fall apart when Apple moves to randomized serialnumbers

**Comment by sphen13** [comment]
trying to decipher your last commit - looks like you are redoing the plugin - will this resolve the issue? thanks!

**Comment by tuxudo** [comment]
This has been resolved (for non-random serial numbers) with v5.0 beta of the module. It is not possible to determine the date of manufacture on Macs with random serial numbers.
