### ISSUE TITLE
FR: change "Can't lookup warranty" to a manual lookup link

### ISSUE THREAD

**Issue by diwanicki** [munkireport/warranty#3]
For those of us without a GSX account, making the Warranty coverage item a clickable link back to Apple, preloaded with serial number, instead of the red "Can't lookup warranty" alert, would be a useful function. 

I am willing to work on this, but not sure where to make the code changes (to check if GSX is enabled, then to build a link to https://checkcoverage.apple.com/in/en?sn= labeled "Manual Check" instead of "Can't lookup warranty").

Saves some typing, even though we still have to do the captcha...

**Comment by bochoven** [comment]
Fixed here 2951b7dd83451ae13a644cabc5a3b5aef7b13cc8
