### ISSUE TITLE
FR: Add warranty information manually

### ISSUE THREAD

**Issue by kevinmcox** [munkireport/warranty#4]
I'd like to suggest an enhancement that would allow admins to manually enter warranty expiration dates in MunkiReport.

This would keep the warranty tracking fields useful despite Apple removing the automated way for this to be checked.

Thanks.

**Comment by bochoven** [comment]
Fixed with 2951b7dd83451ae13a644cabc5a3b5aef7b13cc8

**Comment by kevinmcox** [comment]
Nice, thanks @bochoven!
